# general settings
name: Uformer_flare7kpp_baseline_option.yml
model_type: DeflareModel
scale: 1
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Flare7Kpp
    type: Flare7kpp_origin_Pair_Loader
    image_path: /data/dataset/flaredataset/dataset/Flickr24K #/data/dataset/flaredataset/dataset/Flickr24K-s #Flickr24K
    scattering_dict:
      Flare7k_scattering: /data/dataset/flaredataset/dataset/Flare7Kpp/glare_an2/compound_glare # /data/dataset/flaredataset/dataset/Flare7K/Scattering_Flare/Compound_Flare
      Real_scattering1: /data/dataset/flaredataset/dataset/Flare7Kpp/Flare-R/Compound_Flare
    reflective_dict:
      Flare7k_reflective: /data/dataset/flaredataset/dataset/Flare7Kpp/sigflare/sigflare # /data/dataset/flaredataset/dataset/Flare7K/Reflective_Flare
      Real_reflective1: ~
    light_dict:
      Flare7k_light: /data/dataset/flaredataset/dataset/Flare7Kpp/glare_an2/light_source_small # /data/dataset/flaredataset/dataset/Flare7K/Scattering_Flare/Light_Source
      Real_light1:  /data/dataset/flaredataset/dataset/Flare7Kpp/Flare-R/Light_Source
    data_ratio: [0.5, 0.5] # or [0.6, 0.4], only a ratio is enough
    transform_base:
      img_size: 512
    transform_flare:
      scale_min: 0.7
      scale_max: 1.5
      translate: 300 # translate是指在x和y方向上的平移范围
      shear: 20
    mask_type: ~


    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: flare_test
    type: Image_Pair_Loader_origin
    dataroot_gt: /data/dataset/flaredataset/dataset/Flare7Kpp/test/real/gt_new
    dataroot_lq: /data/dataset/flaredataset/dataset/Flare7Kpp/test/real/input
    gt_size: 512

# network structures
network_g:
  type: Uformer
  img_size: 512
  img_ch: 3
  output_ch: 6
  # multi_stage: 1

# path
path:
  pretrain_network_g: ~ 
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000] # 循环到200000次后，学习率变为原来的0.5
    gamma: 0.5

  out_deflare: True
  ema_decay: 0.9
  total_iter: 600000
  warmup_iter: -1  # no warm up

  # losses
  l1_opt:
    type: L_Abs_pure
    loss_weight: 0.5

  perceptual:
    type: L_percepture
    loss_weight: 0.25 #0.5

#  histogram:
#    type: L_histogram
#    loss_weight: 0.3

# validation settings
val:
  val_freq: !!float 5e2
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  # wandb:
  #   project: flare
  #   resume_id: zj1208

# dist training settings
dist_params:
  backend: nccl
  port: 29500